#!/bin/bash

warcdealerUserName=$(sed '1q;d' "$HOME"/.warcdealer.cfg)
[ "$(whoami)" != "$warcdealerUserName" ] && exec sudo -u "$warcdealerUserName" -- "$0" "$@"

#Archive a Web site's directory recursively
a() { cd ~/grabs/ && grab-site --no-dupespotter --concurrency=5 --wpull-args=--warc-move=~/warcdealer/\ --read-timeout=3600\ --connect-timeout=20\ --dns-timeout=20\ --retry-connrefused\ --retry-dns-error\ --max-redirect=128\ --phantomjs-scroll=50000\ --phantomjs-exe=/phantomjs-1.9.8-linux-x86_64/bin/phantomjs\ --content-on-error\ --tries=1024 "$@"; }
export -f a;

#Archive a single Web page:
o() { cd ~/grabs/ && grab-site --no-dupespotter --concurrency=5 --wpull-args=--warc-move=~/warcdealer/\ --read-timeout=3600\ --connect-timeout=20\ --dns-timeout=20\ --retry-connrefused\ --retry-dns-error\ --max-redirect=128\ --phantomjs-scroll=50000\ --phantomjs-exe=/phantomjs-1.9.8-linux-x86_64/bin/phantomjs\ --content-on-error\ --tries=1024 --1 "$@"; }
export -f o;

#Quick recursive archival (gives up easily on retriable errors; use for urgent jobs to get a quick grab, then run a full archival for thoroughness)
aq() { cd ~/grabs/ && grab-site --no-dupespotter --concurrency=5 --wpull-args=--warc-move=~/warcdealer/\ --read-timeout=3600\ --connect-timeout=20\ --dns-timeout=20\ --retry-connrefused\ --retry-dns-error\ --max-redirect=128\ --phantomjs-scroll=50000\ --phantomjs-exe=/phantomjs-1.9.8-linux-x86_64/bin/phantomjs\ --content-on-error "$@"; }
export -f aq;

#Quick single archival
oq() { cd ~/grabs/ && grab-site --no-dupespotter --concurrency=5 --wpull-args=--warc-move=~/warcdealer/\ --read-timeout=3600\ --connect-timeout=20\ --dns-timeout=20\ --retry-connrefused\ --retry-dns-error\ --max-redirect=128\ --phantomjs-scroll=50000\ --phantomjs-exe=/phantomjs-1.9.8-linux-x86_64/bin/phantomjs\ --content-on-error --1 "$@"; }
export -f oq;

#Archive using PhantomJS
ap() { cd ~/grabs/ && grab-site --no-dupespotter --concurrency=5 --wpull-args=--warc-move=~/warcdealer/\ --read-timeout=3600\ --connect-timeout=20\ --dns-timeout=20\ --retry-connrefused\ --retry-dns-error\ --max-redirect=128\ --phantomjs-scroll=50000\ --phantomjs-exe=/phantomjs-1.9.8-linux-x86_64/bin/phantomjs\ --content-on-error\ --tries=1024\ --phantomjs "$@"; }
export -f ap;

#Archive single page using PhantomJS
op() { cd ~/grabs/ && grab-site --no-dupespotter --concurrency=5 --wpull-args=--warc-move=~/warcdealer/\ --read-timeout=3600\ --connect-timeout=20\ --dns-timeout=20\ --retry-connrefused\ --retry-dns-error\ --max-redirect=128\ --phantomjs-scroll=50000\ --phantomjs-exe=/phantomjs-1.9.8-linux-x86_64/bin/phantomjs\ --content-on-error\ --tries=1024\ --phantomjs --1 "$@"; }
export -f op;

#Start Warcdealer
warcdealer() { ~/.warcdealers }
export -f warcdealer;

#Quickly upload a file to the Internet Archive (for emergencies)
iu() { IUIDENTIFIER=$(python2 -c 'import uuid; print str(uuid.uuid4())')-$(date +%Y.%m.%d.%H.%M.%S.%N)-$(xxd -pu &lt;&lt;&lt; "$(date +%z)"); ia upload $IUIDENTIFIER --metadata="subject:Uploaded using iu v3; 291E5EDE-6B59-4CB7-8928-375368F5725B" "$@"; echo 'https://archive.org/download/'$IUIDENTIFIER; }
export -f iu;
